# Generated by Django 4.2.1 on 2023-07-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet2023_DatosApp', '0002_usuario_remove_jugador_equipo_remove_liga_equipos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
