# Generated by Django 4.2.1 on 2023-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Basquet2023_DatosApp', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('periodista', 'Periodista'), ('tecnico', 'Técnico'), ('jugador', 'Jugador'), ('aficionado', 'Aficionado')], max_length=50)),
            ],
        ),
    ]
